# Generated by Django 5.1.6 on 2025-04-13 14:19

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talent_filter_app", "0002_recruiterprofile_company_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="job",
            old_name="title",
            new_name="job_title",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="department",
            new_name="recruiter_name",
        ),
        migrations.AddField(
            model_name="job",
            name="application_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="application_link",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("Full-time", "Full-time"),
                    ("Part-time", "Part-time"),
                    ("Contract", "Contract"),
                    ("Internship", "Internship"),
                ],
                default="Full-time",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="experience_required",
            field=models.CharField(
                default="Y", max_length=50
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="external_portals",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="how_to_apply",
            field=models.TextField(default="Online"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="job_id",
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="job",
            name="key_responsibilities",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="nice_to_have",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="recruiter_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="recruiter_linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="recruiter_position",
            field=models.CharField(
                default="", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="requirements",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="skills_required",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="summary",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="workplace_type",
            field=models.CharField(
                choices=[
                    ("On-site", "On-site"),
                    ("Remote", "Remote"),
                    ("Hybrid", "Hybrid"),
                ],
                default="Remote",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="open_positions",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[("Open", "Open"), ("Closed", "Closed")],
                default="Open",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="talent_filter_app.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="talent_filter_app.location",
            ),
        ),
    ]
