# Generated by Django 5.1.6 on 2025-05-02 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talent_filter_app", "0006_alter_job_recruiter_jobmatchanalysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="recruiter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="talent_filter_app.recruiterprofile",
            ),
        ),
    ]
