# Generated by Django 5.1.6 on 2025-05-02 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talent_filter_app", "0007_alter_job_recruiter"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_score", models.IntegerField(default=0)),
                ("matching_skills", models.JSONField(default=list)),
                ("missing_skills", models.JSONField(default=list)),
                ("experience_match", models.TextField(blank=True, null=True)),
                ("education_match", models.TextField(blank=True, null=True)),
                ("overall_assessment", models.TextField(blank=True, null=True)),
                ("contact_recommendation", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="talent_filter_app.job",
                    ),
                ),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_recommendations",
                        to="talent_filter_app.jobseekerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-match_score", "-updated_at"],
                "unique_together": {("job", "job_seeker")},
            },
        ),
    ]
